### ISSUE TITLE
Replace audio links with actual audio players

### ISSUE THREAD

**Issue by calebdre** [sci-sim/sci-sim#26]
Right now we just link to the audio tracks, which is confusing for the user due to instructions not being clear. We need have have audio players that plays the track.  

You can find the links to all the audio that'll be used in new_sim_template.txt (just search .mp3)  

You need to extract the mp3 from the site, put it inside a folder, and link to it when it's needed from the PageRenderer

**Comment by mparq** [comment]
I'm looking at new_sim_template.txt on the latest upstream version, but I don't see any audio file links. Is the latest version of that file up on master?

**Comment by calebdre** [comment]
oops, look for http://www.easyauscultation.com/cases-listing-details in the template.
that's where all the audio files we want currently live.

**Comment by Hermestu** [comment]
How many audio files we need to extract?

**Comment by calebdre** [comment]
i'm not sure. There are 24 matches if you search for that keyword, but more than half of those will be the same file. So at most 12.

**Comment by mparq** [comment]
I made a quick script to download the audio files, rename them, and place them into scisim/static/audio. I also replaced all the links in new_sim_template.txt with the new audio file names. Tu, if you want to play around with the actual audio files (there were only 4), check my fork. 

Right now if you look in sim_parser.py, in the add_section function, when the field is "media" (which it will be for our audio files), we add an <a> element to the "sections" of that page. This is when we assumed that any media not a jpg would be a link. However, now we need to change this to be probably some sort of div element with a class and possibly an attribute which will contain our mp3 filename. I don't know if there is a better way to do this, but we need some way to grab the mp3 file associated with our section in the PatientEngine code.

In PageRenderer, maybe we can recognize when a section will be an audioplayer section and add elements to the div to make it a true audioplayer, but let's leave that for later and just have some clickable element for now that will start playing the sounds. I did some research and found the [soundJS library](http://www.createjs.com/tutorials/Basics%20and%20Best%20Practices/). This would be good for us to use since it takes care of browser-specific issues. It also provides a Flash fallback support plugin so that browsers which don't support html5 (<=IE8) will be able to fall back to flash. This is desirable if we're assuming that many schools won't have later versions of IE on their computers.

PatientEngine is where we want to attach the event listeners to the audio player stuff I believe. This might get a little messier if we implement play, pause, etc... but I think we should try to get something working first and worry about abstracting later. We can also worry about "preloading" the mp3 files later if we find it necessary. I think it is good practice to implement, but at the same time, these are very small files and won't be auto-playing so I think we're fine without it. 

What we want to do is figure out how to access the correct music files from the page. Possibly the easiest, if messy, way to do this would be to attach the music filename into a div element or something similar when first parsing the template as previously mentioned. Then, when we're reading through the sections of our page in PageRenderer, if we get an "audio playing" div section, we can access the div element to get the music file. We do some similar checks within the composePage method already. Let me know if you have suggestions for a better way. 

When we get to a page which has mp3 files associated with it, we need to register them with soundJS.Sound.registerSounds or registerSound. After this, we need to attach an onclick listener to that div (or whatever we decide to use for this) that will call soundJS.Sound.play(soundID), where soundID refers to the ID (alternatively src location) of the sound we want to play.You'll see in a lot of the examples in the soundJS documentation, that they attach a listener for the "fileload" event that is thrown when a sound is done loading, but we won't be auto-playing the sounds so we don't need to worry about that for now. Let's get this working first, and then we can add in other functionality including support for flash fallback.

More documentation on Sound class: http://www.createjs.com/docs/soundjs/classes/Sound.html#method_play

**Comment by calebdre** [comment]
wouldn't it be easier to have an audio player class that handles all of the audio stuff: Event listeners and file fetchers and all? In the PageRenderer, you can listen for when you need to put in an audio clip and then instantiate a new instance of the audio player class. The class can have all of the audio file names stored and figure out based on the context somehow which file needs to be played.  

SoundJS looks very promising though.

**Comment by mparq** [comment]
Actually, you're right! That does sound a lot better.

**Comment by mparq** [comment]
Made a pull request. However, we still need to figure out how to enable FlashPlayerAudio plugin fallback with soundJS. This might involve having to place a .swf somewhere in our project. Alternatively, or additionally, we should add in a handler for when the browser can't play audio. More functionality can be added as needed.

**Comment by mparq** [comment]
One more thing: In this link http://www.createjs.com/docs/soundjs/classes/Sound.html. If you scroll down to Known Issues, it seems that mp3 files don't always work especially for firefox. We might want to see if we can convert our mp3s to ogg to use as a fallback, and do some testing on a Windows machine with Internet Explorer since this is probably to environment most students would be viewing the site in.

**Comment by calebdre** [comment]
Let's make it so if the mp3 doesn't work, it'll give them a link to the audio file on our server. [pages like these](http://d2ik8svv2swg1p.cloudfront.net/courses/5001.mp3) . I think converting the files is a good idea. 

Dr. Peffer will be looking at the simulation tonight and i think she will be using a windows machine, so we'll see how that goes for her.

**Comment by calebdre** [comment]
fixed for now in pull #32
