### ISSUE TITLE
Make the simulation items more consistent

### ISSUE THREAD

**Issue by calebdre** [sci-sim/sci-sim#33]
From Dr. Peffer:

> Some of the residents have 7 tests that you can perform in the first half--Ms. Watson has all 8 and I think she is the only one with all 8. I also noticed that for Mr. Smith you have to do 4 tests and for the rest, you have to do 3 to move on. Everything in the second half looks more consistent.  

Translating it to this template language was a long and arduous task and very prone to error. We need to make the simulation more consistent. You should only need to edit the new_sim_template.txt file

**Comment by mparq** [comment]
It seems there are some inconsistencies regarding feet tests in the first half. I see some choices for Checking feet for sensation, and some for checking feet for sores. Which do we want to use? We're also missing:
- Page for Asking Mr. Smith how he feels? (burningfeet?) I filled in something as a placeholder, but need to ask Dr. Peffer what she wanted there.
- Ms. Williams was missing the page for her feet test. I filled in an "unhealthy" one.
- Ms. Jones is missing her page for the temperature test.

The residents having 7 tests were coming from the feet tests not being hooked to a correct page. I hooked up most of the patients to a generic check feet test. (seems like it's the check sores test). I changed Mr. Smith's minimum choices required to 3. I also scripted a cleanup of new_sim_template.txt for human reading. Unfortunately, now I wish I hadn't done that just yet because it will be less obvious what I actually changed through the commit history...

**Comment by calebdre** [comment]
Your changes look good on the simulation - Jones and Smith were missing a choice and so i added them on the master branch. That made it so that it so that you have to edit your commit though :/

**Comment by mparq** [comment]
Merged those changes into new_sim_template.txt. I might be doing something wrong when I rebase, because it always repeats commits I've already pushed to my master. Should I be doing something different like just pulling?

**Comment by calebdre** [comment]
i'm not quite sure what goes on there - I've had that problem too but i've never looked into it.  
Let's leave it for now as long as it works
